spring.application.name=dating

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.actuate=DEBUG

# JPA/Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Database connection properties (example for H2)
spring.datasource.url=jdbc:h2:mem:dating;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console